In [9]:
import numpy as np
np.__version__

'2.0.2'

In [10]:
a:int = 1;

In [11]:
type(a)

int

In [12]:
L = list(range(10))

In [13]:
type(L[0])

int

In [14]:
L2 = [str(c) for c in L]

In [15]:
print(L2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [16]:
type(L[0])

int

In [17]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [18]:
import array
l = list(range(10));
l1 = [str(a) for a  in l]
l1
A = array.array('u',l1);
print(A)

B = array.array('i',l)
B

array('u', '0123456789')


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Numpy
import numpy as np

In [20]:
np.array([1,2,1.1]) 

array([1. , 2. , 1.1])

In [21]:
fl_arr = np.array([1,2,3],dtype=np.float32)
fl_arr

array([1., 2., 3.], dtype=float32)

In [22]:
# Multidiementional

multi_d_arr = np.array([range(i,i+2) for i in [2,4,6,5]])

In [23]:
len(multi_d_arr)
# len? #length

4

In [24]:
multi_d_arr.shape

(4, 2)

In [25]:
multi_d_arr

array([[2, 3],
       [4, 5],
       [6, 7],
       [5, 6]])

In [35]:
test_d_arr = np.array([[[1,2],[2,3],[1,2]],[[2,2],[3,2],[1,2]]])

In [36]:
test_d_arr.shape

(2, 3, 2)