In [1]:
import numpy as np

In [5]:
rng = np.random.default_rng(seed=1701) # seed for reproducibility
# Construct a new Generator with the default BitGenerator
print(rng)

Generator(PCG64)


In [7]:
x1 = rng.integers(10,size=6) #`  1D array`
x2  = rng.integers(10,size=(3,4)) # 2D array
x3 = rng.integers(10,size=(3,4,5)) # 3D array

In [9]:
print(x3);
print("x3 Shape: ", x3.shape)
print("x3 Size: ", x3.size)
print("x3 Dimension: ", x3.ndim)
print("x3 Data type: ", x3.dtype)

[[[4 3 5 5 0]
  [8 3 5 2 2]
  [1 8 8 5 3]
  [0 0 8 5 8]]

 [[5 1 6 2 3]
  [1 2 5 6 2]
  [5 2 7 9 3]
  [5 6 0 2 0]]

 [[2 9 4 3 9]
  [9 2 2 4 0]
  [0 3 0 0 2]
  [3 2 7 4 7]]]
x3 Shape:  (3, 4, 5)
x3 Size:  60
x3 Dimension:  3
x3 Data type:  int64


In [52]:
# same indexing with numpy array
test =[1,2,3,4];
test2 = [[2,2],[1,1]];
print(type(test))
test[-2]


# print(test2[0,1])
print(test[0:4])

<class 'list'>
[1, 2, 3, 4]


In [32]:
# Indexing
print("X1:",x1)
print(x1[0])

print("X2 :",x2)
print(x2[0][0])
print(x2[1])

print(x2[-1])
print(x2[-2][-1])
print(x2[:])


X1: [9 4 0 3 8 6]
9
X2 : [[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
3
[4 0 2 3]
[0 0 6 9]
3
[[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]


In [41]:
#unlike from listing > numpy array can ne access using comma-separated(row,col) tuple
print(x2)
print(x2[2,-1])

# modified
x2[-1,-1] = 12;
print(x2[-1])

[[ 3  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6 10]]
10
[ 0  0  6 12]
